name: Docker Image CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dockerImage: eu.gcr.io/personalweb-279207/minilang-to-java
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Gradle Build
        run: ./gradlew build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/test-results/**/*.xml"

      - name: Build Docker Image
        env:
          BUILD_ID: "${{ github.run_id }}"
          DOCKER_IMAGE_TAG: "${{ env.dockerImage }}"
        run: ./gradlew dockerBuildImage

      - name: Docker Login
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run: echo $DOCKER_PASSWORD | docker login -u _json_key --password-stdin https://eu.gcr.io

      - name: Docker Push
        if: github.ref == 'refs/heads/main'
        run: docker image push --all-tags "${{ env.dockerImage }}"
